"""
face_recognition_module.py
--------------------------
Modul inti Fase 1 — Face Recognition Pipeline:
    SCRFD (deteksi wajah) → ArcFace (embedding) → FAISS (1:N search) → threshold τ

Public API
----------
    module = FaceRecognitionModule()

    result = module.recognize_face(frame)
    # {"status": "known"|"unknown", "customer_id": str|None, "score": float}

    result = module.enroll_face(frame, customer_id)
    # {"success": bool, "message": str, "embedding": list[float]|None}

    stats  = module.get_gallery_stats()
    # {"n_people": int, "n_embeddings": int, "people": list[str]}

    module.reload_gallery()   # call after adding a new embedding to disk/DB

Architecture
------------
    Detector  : InsightFace buffalo_l / det_10g.onnx  — SCRFD-10GF
    Recognizer: InsightFace buffalo_l / w600k_r50.onnx — ArcFace R50, WebFace600K
    Alignment : insightface.utils.face_align.norm_crop (5-point landmark → 112x112)
    Search    : FAISS IndexFlatIP  (inner-product ≡ cosine similarity on L2-normed vecs)
    Threshold : τ auto-loaded from results/arcface_results.txt (EER-based, τ=0.258)

Storage (privacy-preserving, sesuai UU PDP)
-------------------------------------------
    Only 512-d embeddings are stored — NO raw photos ever written by this module.
    Gallery lives in Supabase (embeddings table) via the CRM, loaded into FAISS at startup.
    Local .npy files in embeddings/arcface/ are also supported for offline/dev use.
"""

from __future__ import annotations

import logging
import os
import sys
import time
from pathlib import Path
from typing import Optional

import cv2
import numpy as np

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)

# ── Path resolution ───────────────────────────────────────────────────────────
# Works whether imported from root or from scripts/
_HERE = Path(__file__).resolve().parent
PROJECT_ROOT = _HERE
EMBEDDINGS_DIR = PROJECT_ROOT / "embeddings" / "arcface"
RESULTS_FILE   = PROJECT_ROOT / "results" / "arcface_results.txt"

# ── FAISS (optional graceful fallback to numpy) ───────────────────────────────
try:
    import faiss
    _USE_FAISS = True
except ImportError:
    _USE_FAISS = False
    logger.warning("faiss not installed — falling back to numpy cosine search. "
                   "Install with: pip install faiss-cpu")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _l2_normalize(vec: np.ndarray) -> np.ndarray:
    norm = np.linalg.norm(vec)
    return (vec / (norm + 1e-10)).astype(np.float32)


def _load_eer_threshold(default: float = 0.35) -> float:
    """Read eer_threshold from results/arcface_results.txt (generated by evaluate.py)."""
    if RESULTS_FILE.exists():
        with open(RESULTS_FILE) as f:
            for line in f:
                if line.startswith("eer_threshold"):
                    try:
                        val = float(line.split(":")[1].strip())
                        logger.info(f"[Threshold] Loaded EER threshold τ = {val:.4f} from {RESULTS_FILE.name}")
                        return val
                    except ValueError:
                        pass
    logger.warning(f"[Threshold] Could not read from {RESULTS_FILE} — using default τ = {default}")
    return default


# ── Core class ────────────────────────────────────────────────────────────────

class FaceRecognitionModule:
    """
    Plug-and-play face recognition module for Cafe FaceRec.

    Usage:
        module = FaceRecognitionModule()

        # From a live BGR frame (OpenCV):
        result = module.recognize_face(frame)

        # Enroll a new customer from a BGR frame:
        result = module.enroll_face(frame, customer_id="uuid-or-name")
    """

    def __init__(
        self,
        det_size: tuple[int, int] = (320, 320),
        det_thresh: float = 0.5,
        threshold: Optional[float] = None,
    ):
        """
        Parameters
        ----------
        det_size   : SCRFD input size. (320, 320) = fast; (640, 640) = accurate.
        det_thresh : Minimum SCRFD detection confidence to accept a face.
        threshold  : Cosine similarity tau. None = auto-load from EER results.
        """
        self.det_thresh = det_thresh
        self.threshold  = threshold if threshold is not None else _load_eer_threshold()

        sys.path.insert(0, str(PROJECT_ROOT))
        from models import _DirectArcFaceONNX, _download_pack, _find_onnx

        # ── Load SCRFD detector ────────────────────────────────────────────────
        logger.info("[SCRFD] Loading detector (buffalo_l / det_10g.onnx) ...")
        _download_pack("buffalo_l")
        _det_path = _find_onnx("buffalo_l", "det_10g.onnx")
        print(f"  [MODEL] {_det_path}")
        import onnxruntime as _ort
        _det_so = _ort.SessionOptions()
        _det_so.enable_mem_pattern   = False
        _det_so.enable_cpu_mem_arena = False
        from insightface.model_zoo import get_model as _gm
        self._detector_raw = _gm(_det_path, session_options=_det_so, providers=["CPUExecutionProvider"])
        self._detector_raw.prepare(0, input_size=det_size)
        logger.info("[SCRFD] Detector ready.")

        # ── Trim process working set (Windows) ────────────────────────────────
        try:
            import ctypes
            ctypes.windll.psapi.EmptyWorkingSet(
                ctypes.windll.kernel32.GetCurrentProcess()
            )
            logger.debug("[Init] Process working set trimmed.")
        except Exception:
            pass

        # ── Load ArcFace recognizer ────────────────────────────────────────────
        logger.info("[ArcFace] Loading recognizer (buffalo_l / w600k_r50.onnx) ...")
        _download_pack("buffalo_l")
        _arcface_path = _find_onnx("buffalo_l", "w600k_r50.onnx")
        self._recognizer = _DirectArcFaceONNX(_arcface_path)
        logger.info("[ArcFace] Recognizer ready.")

        # ── Load face_align ────────────────────────────────────────────────────
        from insightface.utils import face_align as _fa
        self._face_align = _fa

        # ── Build FAISS gallery ────────────────────────────────────────────────
        self._labels: list[str]          = []   # customer_id per row
        self._gallery: Optional[np.ndarray] = None  # (N, 512) float32
        self._index   = None
        self._load_local_gallery()

        logger.info(
            f"[Gallery] {self.get_gallery_stats()['n_embeddings']} embeddings "
            f"| {self.get_gallery_stats()['n_people']} people "
            f"| threshold τ = {self.threshold:.4f}"
        )

    # ── Gallery management ────────────────────────────────────────────────────

    def _load_local_gallery(self):
        """
        Load gallery from local .npy files in embeddings/arcface/.
        Each file: <customer_id>.npy  shape (n_shots, 512).
        Also called by reload_gallery().
        """
        labels: list[str] = []
        vecs: list[np.ndarray] = []

        if EMBEDDINGS_DIR.is_dir():
            for fpath in sorted(EMBEDDINGS_DIR.glob("*.npy")):
                customer_id = fpath.stem
                arr = np.load(fpath).astype(np.float32)  # (n, 512)
                if arr.ndim == 1:
                    arr = arr[np.newaxis, :]
                for vec in arr:
                    labels.append(customer_id)
                    vecs.append(_l2_normalize(vec))

        if not vecs:
            logger.info("[Gallery] Empty — no .npy files found in embeddings/arcface/. "
                        "Enroll customers first or load from DB via load_gallery_from_rows().")
            self._labels  = []
            self._gallery = np.zeros((0, 512), dtype=np.float32)
            self._index   = None
            return

        self._labels  = labels
        self._gallery = np.stack(vecs).astype(np.float32)
        self._build_index()

    def load_gallery_from_rows(self, rows: list[tuple[str, list[float]]]):
        """
        Load gallery from external data (e.g., from Supabase via CRM service).

        Parameters
        ----------
        rows : list of (customer_id: str, embedding_vector: list[float])
        """
        labels: list[str] = []
        vecs: list[np.ndarray] = []
        for customer_id, vec in rows:
            labels.append(customer_id)
            vecs.append(_l2_normalize(np.array(vec, dtype=np.float32)))
        self._labels  = labels
        self._gallery = np.stack(vecs).astype(np.float32) if vecs else np.zeros((0, 512), dtype=np.float32)
        self._build_index()
        logger.info(f"[Gallery] Loaded {len(labels)} embeddings from external rows.")

    def reload_gallery(self):
        """Reload gallery from local .npy files (call after enrollment)."""
        self._load_local_gallery()
        logger.info(f"[Gallery] Reloaded — {len(self._labels)} embeddings.")

    def _build_index(self):
        if self._gallery is None or len(self._gallery) == 0:
            self._index = None
            return
        if _USE_FAISS:
            self._index = faiss.IndexFlatIP(512)
            self._index.add(self._gallery)
        else:
            self._index = None  # numpy fallback handled in _search()

    def get_gallery_stats(self) -> dict:
        return {
            "n_embeddings": len(self._labels),
            "n_people": len(set(self._labels)),
            "people": sorted(set(self._labels)),
        }

    # ── Face pipeline ─────────────────────────────────────────────────────────

    def _get_faces(self, frame: np.ndarray) -> list:
        """Run SCRFD raw detector and wrap results in Face objects."""
        from insightface.app.common import Face
        bboxes, kps = self._detector_raw.detect(frame, max_num=0, metric='default')
        if bboxes is None or len(bboxes) == 0:
            return []
        faces = []
        for i in range(bboxes.shape[0]):
            bbox = bboxes[i, :4]
            det_score = float(bboxes[i, 4])
            if det_score >= self.det_thresh:
                faces.append(Face(bbox=bbox, kps=kps[i] if kps is not None else None, det_score=det_score))
        return faces

    def _detect_and_align(self, frame: np.ndarray):
        """
        Run SCRFD on frame.
        Returns aligned 112x112 BGR crop + face object, or (None, None) if no face.
        """
        faces = self._get_faces(frame)
        if not faces:
            return None, None
        face = max(faces, key=lambda f: f.det_score)
        try:
            aligned = self._face_align.norm_crop(frame, face.kps, image_size=112)
        except Exception as e:
            logger.warning(f"[Align] norm_crop failed: {e}")
            return None, None
        return aligned, face

    def _get_embedding(self, aligned_112: np.ndarray) -> np.ndarray:
        """ArcFace embedding — returns L2-normalized 512-d float32 vector."""
        emb = self._recognizer.get_feat(aligned_112).flatten()
        return _l2_normalize(emb)

    def _search(self, probe: np.ndarray) -> tuple[str | None, float]:
        """
        1:N FAISS (or numpy) search.
        Returns (customer_id, score) — customer_id is None if gallery is empty or score < τ.
        """
        if not self._labels or self._gallery is None or len(self._gallery) == 0:
            return None, 0.0

        if _USE_FAISS and self._index is not None:
            D, I = self._index.search(probe.reshape(1, -1), k=1)
            score = float(D[0][0])
            idx   = int(I[0][0])
        else:
            sims  = self._gallery @ probe
            idx   = int(np.argmax(sims))
            score = float(sims[idx])

        if score >= self.threshold:
            return self._labels[idx], score
        return None, score

    # ── Public API ────────────────────────────────────────────────────────────

    def recognize_face(self, frame: np.ndarray) -> dict:
        """
        Core Fase 1 deliverable.

        Parameters
        ----------
        frame : BGR image (OpenCV format, any resolution).

        Returns
        -------
        dict with keys:
            status      : "known" | "unknown" | "no_face"
            customer_id : str (matched customer_id) or None
            score       : float (cosine similarity, 0–1 range for L2-normalized vecs)
            det_score   : float (SCRFD detection confidence) or None
        """
        aligned, face = self._detect_and_align(frame)
        if aligned is None:
            return {"status": "no_face", "customer_id": None, "score": 0.0, "det_score": None}

        try:
            probe = self._get_embedding(aligned)
        except Exception as e:
            logger.error(f"[recognize_face] Embedding failed: {e}")
            return {"status": "no_face", "customer_id": None, "score": 0.0, "det_score": float(face.det_score)}

        customer_id, score = self._search(probe)

        return {
            "status":      "known"   if customer_id else "unknown",
            "customer_id": customer_id,
            "score":       round(score, 6),
            "det_score":   round(float(face.det_score), 4),
        }

    def extract_embedding_from_frame(self, frame: np.ndarray) -> dict:
        """
        Extract embedding from a frame WITHOUT searching the gallery.
        Used by /extract-embedding and enrollment endpoints.

        Returns
        -------
        dict:
            success   : bool
            embedding : list[float] (512-d) or None
            det_score : float or None
            message   : str
        """
        aligned, face = self._detect_and_align(frame)
        if aligned is None:
            return {"success": False, "embedding": None, "det_score": None, "message": "No face detected"}
        try:
            emb = self._get_embedding(aligned)
            return {
                "success":   True,
                "embedding": emb.tolist(),
                "det_score": round(float(face.det_score), 4),
                "message":   "OK",
            }
        except Exception as e:
            logger.error(f"[extract_embedding] {e}")
            return {"success": False, "embedding": None, "det_score": float(face.det_score), "message": str(e)}

    def enroll_face(self, frame: np.ndarray, customer_id: str, append: bool = True) -> dict:
        """
        Extract embedding from frame and save it to embeddings/arcface/<customer_id>.npy.
        Privacy-preserving: only the 512-d vector is stored, never the photo.

        Parameters
        ----------
        frame       : BGR image.
        customer_id : Unique ID (UUID from Supabase or display name).
        append      : If True, add to existing .npy (multiple shots per customer).
                      If False, overwrite.

        Returns
        -------
        dict:
            success          : bool
            message          : str
            embedding        : list[float] or None  (512-d vector, send to CRM to store in DB)
            embeddings_saved : int  (total embeddings now stored for this customer)
        """
        result = self.extract_embedding_from_frame(frame)
        if not result["success"]:
            return {
                "success": False,
                "message": result["message"],
                "embedding": None,
                "embeddings_saved": 0,
            }

        emb = np.array(result["embedding"], dtype=np.float32)
        EMBEDDINGS_DIR.mkdir(parents=True, exist_ok=True)
        npy_path = EMBEDDINGS_DIR / f"{customer_id}.npy"

        if append and npy_path.exists():
            existing = np.load(npy_path).astype(np.float32)
            if existing.ndim == 1:
                existing = existing[np.newaxis, :]
            combined = np.vstack([existing, emb[np.newaxis, :]])
        else:
            combined = emb[np.newaxis, :]

        np.save(npy_path, combined)
        n_saved = combined.shape[0]

        # Hot-reload gallery so new customer is searchable immediately
        self.reload_gallery()

        logger.info(f"[Enroll] '{customer_id}' — {n_saved} embedding(s) stored at {npy_path}")
        return {
            "success":          True,
            "message":          f"Enrolled '{customer_id}' — {n_saved} embedding(s) stored.",
            "embedding":        result["embedding"],   # return vector for CRM to persist in Supabase
            "embeddings_saved": n_saved,
        }

    # ── Utility: draw overlays (for live_demo / api_server video feed) ────────

    def annotate_frame(self, frame: np.ndarray, result: dict) -> np.ndarray:
        """
        Draw bounding box + label on frame.
        Runs SCRFD again on the frame — use only for display, not production throughput.
        """
        faces = self._get_faces(frame)
        if not faces:
            return frame

        face  = max(faces, key=lambda f: f.det_score)
        x1, y1, x2, y2 = face.bbox.astype(int)

        status = result.get("status", "no_face")
        score  = result.get("score", 0.0)
        cid    = result.get("customer_id", "")

        if status == "known":
            color = (70, 210, 90)
            label = f"{cid}  {score:.2f}"
        elif status == "unknown":
            color = (30, 190, 255)
            label = f"Unknown  {score:.2f}"
        else:
            color = (60, 60, 220)
            label = "No face"

        out = frame.copy()
        cv2.rectangle(out, (x1, y1), (x2, y2), color, 2)
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.55, 1)
        cv2.rectangle(out, (x1, y1 - th - 10), (x1 + tw + 8, y1), color, -1)
        cv2.putText(out, label, (x1 + 4, y1 - 5),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, (20, 20, 20), 1, cv2.LINE_AA)
        return out


# ── CLI self-test ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    """
    Quick self-test: open webcam, run recognition, print results to console.
    Press Q to quit.

    Usage:
        python face_recognition_module.py
        python face_recognition_module.py --threshold 0.30
    """
    import argparse
    parser = argparse.ArgumentParser(description="FaceRecognitionModule self-test (webcam)")
    parser.add_argument("--threshold", type=float, default=None,
                        help="Override τ threshold (default: auto from EER results)")
    parser.add_argument("--det-size", type=int, default=320,
                        help="SCRFD input size (320 or 640, default: 320)")
    args = parser.parse_args()

    print("\n" + "="*60)
    print("  Cafe FaceRec — Fase 1 Self-Test")
    print("="*60)
    module = FaceRecognitionModule(
        det_size=(args.det_size, args.det_size),
        threshold=args.threshold,
    )

    stats = module.get_gallery_stats()
    print(f"\n  Gallery: {stats['n_embeddings']} embeddings | {stats['n_people']} people")
    print(f"  People : {stats['people']}")
    print(f"  τ      : {module.threshold:.4f}")
    print(f"\n  Press Q to quit.\n")

    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH,  1280)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

    INTERVAL    = 4
    frame_count = 0
    last_result = {"status": "no_face", "customer_id": None, "score": 0.0, "det_score": None}
    t0 = time.time()

    while True:
        ret, frame = cap.read()
        if not ret:
            continue
        frame_count += 1

        if frame_count % INTERVAL == 0:
            last_result = module.recognize_face(frame)
            elapsed = time.time() - t0
            print(f"  [{elapsed:6.1f}s] {last_result}")

        display = module.annotate_frame(frame, last_result)

        # HUD
        cv2.putText(display,
                    f"τ={module.threshold:.3f}  |  {stats['n_people']} people  |  Q=quit",
                    (10, 25), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (200, 200, 200), 1)
        cv2.imshow("FaceRec Self-Test", display)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    cap.release()
    cv2.destroyAllWindows()
    print("\n[DONE] Self-test finished.")
